// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/rtbv1/rtb.proto

package rtbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BidFloor      float64                `protobuf:"fixed64,2,opt,name=bid_floor,json=bidFloor,proto3" json:"bid_floor,omitempty"`          // CPM; 0 = no floor. Enforced ENGINE-SIDE.
	BidFloorCur   string                 `protobuf:"bytes,3,opt,name=bid_floor_cur,json=bidFloorCur,proto3" json:"bid_floor_cur,omitempty"` // v1: "USD" only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_rtbv1_rtb_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetBidFloor() float64 {
	if x != nil {
		return x.BidFloor
	}
	return 0
}

func (x *Item) GetBidFloorCur() string {
	if x != nil {
		return x.BidFloorCur
	}
	return ""
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // correlation ID: every log line, metric label, bidder call
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // v1: exactly one
	Tmax          int32                  `protobuf:"varint,3,opt,name=tmax,proto3" json:"tmax,omitempty"`  // INFORMATIONAL ONLY — gRPC deadline is authoritative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_rtbv1_rtb_proto_rawDescGZIP(), []int{1}
}

func (x *BidRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BidRequest) GetTmax() int32 {
	if x != nil {
		return x.Tmax
	}
	return 0
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Cur           string                 `protobuf:"bytes,4,opt,name=cur,proto3" json:"cur,omitempty"` // v1: "USD" only
	SeatId        string                 `protobuf:"bytes,5,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_rtbv1_rtb_proto_rawDescGZIP(), []int{2}
}

func (x *Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bid) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Bid) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Bid) GetCur() string {
	if x != nil {
		return x.Cur
	}
	return ""
}

func (x *Bid) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type Seatbid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          string                 `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Bid           []*Bid                 `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seatbid) Reset() {
	*x = Seatbid{}
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seatbid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seatbid) ProtoMessage() {}

func (x *Seatbid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seatbid.ProtoReflect.Descriptor instead.
func (*Seatbid) Descriptor() ([]byte, []int) {
	return file_proto_rtbv1_rtb_proto_rawDescGZIP(), []int{3}
}

func (x *Seatbid) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *Seatbid) GetBid() []*Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // must echo BidRequest.id
	Seatbid       []*Seatbid             `protobuf:"bytes,2,rep,name=seatbid,proto3" json:"seatbid,omitempty"` // empty = no bid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rtbv1_rtb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_rtbv1_rtb_proto_rawDescGZIP(), []int{4}
}

func (x *BidResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidResponse) GetSeatbid() []*Seatbid {
	if x != nil {
		return x.Seatbid
	}
	return nil
}

var File_proto_rtbv1_rtb_proto protoreflect.FileDescriptor

const file_proto_rtbv1_rtb_proto_rawDesc = "" +
	"\n" +
	"\x15proto/rtbv1/rtb.proto\x12\x06rtb.v1\"W\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbid_floor\x18\x02 \x01(\x01R\bbidFloor\x12\"\n" +
	"\rbid_floor_cur\x18\x03 \x01(\tR\vbidFloorCur\"T\n" +
	"\n" +
	"BidRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.rtb.v1.ItemR\x05items\x12\x12\n" +
	"\x04tmax\x18\x03 \x01(\x05R\x04tmax\"o\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03cur\x18\x04 \x01(\tR\x03cur\x12\x17\n" +
	"\aseat_id\x18\x05 \x01(\tR\x06seatId\"<\n" +
	"\aSeatbid\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\tR\x04seat\x12\x1d\n" +
	"\x03bid\x18\x02 \x03(\v2\v.rtb.v1.BidR\x03bid\"H\n" +
	"\vBidResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\aseatbid\x18\x02 \x03(\v2\x0f.rtb.v1.SeatbidR\aseatbid2;\n" +
	"\x06Bidder\x121\n" +
	"\x06GetBid\x12\x12.rtb.v1.BidRequest\x1a\x13.rtb.v1.BidResponseB2Z0github.com/ServerCrash358/rtb-engine/proto/rtbv1b\x06proto3"

var (
	file_proto_rtbv1_rtb_proto_rawDescOnce sync.Once
	file_proto_rtbv1_rtb_proto_rawDescData []byte
)

func file_proto_rtbv1_rtb_proto_rawDescGZIP() []byte {
	file_proto_rtbv1_rtb_proto_rawDescOnce.Do(func() {
		file_proto_rtbv1_rtb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rtbv1_rtb_proto_rawDesc), len(file_proto_rtbv1_rtb_proto_rawDesc)))
	})
	return file_proto_rtbv1_rtb_proto_rawDescData
}

var file_proto_rtbv1_rtb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rtbv1_rtb_proto_goTypes = []any{
	(*Item)(nil),        // 0: rtb.v1.Item
	(*BidRequest)(nil),  // 1: rtb.v1.BidRequest
	(*Bid)(nil),         // 2: rtb.v1.Bid
	(*Seatbid)(nil),     // 3: rtb.v1.Seatbid
	(*BidResponse)(nil), // 4: rtb.v1.BidResponse
}
var file_proto_rtbv1_rtb_proto_depIdxs = []int32{
	0, // 0: rtb.v1.BidRequest.items:type_name -> rtb.v1.Item
	2, // 1: rtb.v1.Seatbid.bid:type_name -> rtb.v1.Bid
	3, // 2: rtb.v1.BidResponse.seatbid:type_name -> rtb.v1.Seatbid
	1, // 3: rtb.v1.Bidder.GetBid:input_type -> rtb.v1.BidRequest
	4, // 4: rtb.v1.Bidder.GetBid:output_type -> rtb.v1.BidResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rtbv1_rtb_proto_init() }
func file_proto_rtbv1_rtb_proto_init() {
	if File_proto_rtbv1_rtb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rtbv1_rtb_proto_rawDesc), len(file_proto_rtbv1_rtb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rtbv1_rtb_proto_goTypes,
		DependencyIndexes: file_proto_rtbv1_rtb_proto_depIdxs,
		MessageInfos:      file_proto_rtbv1_rtb_proto_msgTypes,
	}.Build()
	File_proto_rtbv1_rtb_proto = out.File
	file_proto_rtbv1_rtb_proto_goTypes = nil
	file_proto_rtbv1_rtb_proto_depIdxs = nil
}
